* CLTC20002_YufengLin2025T2_Assignment_2
** Week 01
- Activity 1
  + Are your ideas about assessment the same now?
    After learning the content this week and read the provided
    article, now agree with "Assessment Identity Is Dynamic and Multidimensional"
    and it always evolves over time and is inluenced by personal
    experiences. Professional context and other factors.

    The Assessment is a sociocultural and contextual activity. It is a
    technical process and deeply inflencey by crriculum expectations
    and community balues. The assignment shapes and is shaped by the
    identities of both learners and teachers.

    We believe that assessment is more than measurement now. It is a
    process to determine what students know and can do and achieve.
    The assessment serves multiple purposes, such as formative and
    summative. 
  + Do you think that assessment has the same purpose and intentions
    as it did back then?
    No, as the the paper convincingly argues, the purpose and intentions of assessment are now understood to be far more complex, personal, and deeply integrated into the very fabric of teaching and learning than they were in the past. The focus has shifted from merely what teachers know how to do to who they are as assessors.
    
  + To what extent have your attitudes to assessment changed since
    becoming an educator?
    From this study, the change could be deep and comprehensive. It is
    not only that I've added new techniques to my existing toolkit. My key beliefs about the purpose of assessment (from auditing to guiding), my role within it (from judge to coach), and my understanding of its impact (from academic to ontological, affecting student identity) have all been radically reshaped by experience, reflection, and engaging with the exact kind of research presented in this paper.

    My attitude is now less about "How do I test well?" and more about "How does assessment help us all grow?"
  + Do you believe your attitude is influenced by your own experience?
    Yes, my attitude is deeply influenced by experience since I first
    started teaching in 2008. My initial view of assessment was narrow
    and heavily influenced by my own experiences as a student. Now, I see assessment as the engine of learning, not just the finish line. 


  + What other elements may influence your beliefs about assessment?
    Here are some other elements:
    1. The university culture "To be what you want to be"
    2. Ongoing Learning and professional development
    3. The improvement of my understanding of L&T philosophy. 
